### ISSUE TITLE
Cannot find `set` from standard libraries

### ISSUE THREAD

**Issue by ParadoxV5** [ruby/rbs#1250]
```
$ cat Gemfile
source 'https://rubygems.org'
gem 'rbs'
$ cat Gemfile.lock
GEM
  remote: https://rubygems.org/
  specs:
    rbs (3.0.0)

PLATFORMS
  x86_64-linux

DEPENDENCIES
  rbs

BUNDLED WITH
   2.4.7
$ cat rbs_collection.yaml
path: .gem_rbs_collection
sources: []
$ rbs collection install
/usr/local/lib/ruby/gems/3.2.0/gems/rbs-3.0.0/lib/rbs/collection/config/lockfile_generator.rb:156:in `assign_stdlib': Cannot find `set` from standard libraries (RuntimeError)
        from /usr/local/lib/ruby/gems/3.2.0/gems/rbs-3.0.0/lib/rbs/collection/config/lockfile_generator.rb:129:in `block in assign_gem'
        from /usr/local/lib/ruby/gems/3.2.0/gems/rbs-3.0.0/lib/rbs/collection/config/lockfile_generator.rb:128:in `each'
        from /usr/local/lib/ruby/gems/3.2.0/gems/rbs-3.0.0/lib/rbs/collection/config/lockfile_generator.rb:128:in `assign_gem'
        from /usr/local/lib/ruby/gems/3.2.0/gems/rbs-3.0.0/lib/rbs/collection/config/lockfile_generator.rb:79:in `block in generate'
        from /usr/local/lib/ruby/gems/3.2.0/gems/rbs-3.0.0/lib/rbs/collection/config/lockfile_generator.rb:73:in `each'
        from /usr/local/lib/ruby/gems/3.2.0/gems/rbs-3.0.0/lib/rbs/collection/config/lockfile_generator.rb:73:in `generate'
        from /usr/local/lib/ruby/gems/3.2.0/gems/rbs-3.0.0/lib/rbs/collection/config/lockfile_generator.rb:27:in `generate'
        from /usr/local/lib/ruby/gems/3.2.0/gems/rbs-3.0.0/lib/rbs/collection/config.rb:36:in `generate_lockfile'
        from /usr/local/lib/ruby/gems/3.2.0/gems/rbs-3.0.0/lib/rbs/cli.rb:1068:in `run_collection'
        from /usr/local/lib/ruby/gems/3.2.0/gems/rbs-3.0.0/lib/rbs/cli.rb:135:in `run'
        from /usr/local/lib/ruby/gems/3.2.0/gems/rbs-3.0.0/exe/rbs:7:in `<top (required)>'
        from /usr/local/bin/rbs:25:in `load'
        from /usr/local/bin/rbs:25:in `<main>'
```

Relates to c24d6ee (#1240) – probably have missed a few spots when promoting `set` from `stdlib` to `core`, such as
* [ ] https://github.com/ruby/rbs/blob/v3.0.0/lib/rbs/collection/config/lockfile_generator.rb#L142
* [ ] https://github.com/ruby/rbs/blob/v3.0.0/sig/manifest.yaml#L3

I tested with `rbs`, but this error probably occurs with any gem that depends on `set`.
A workaround is to exclude `rbs` from `rbs collection` but this may not be desirable for the other gems.

**Comment by pocke** [comment]
We had the same issue as rubygems library. https://github.com/ruby/rbs/pull/1107
`rubygems` is ignored with a warning since this PR even if `manifest.yaml` contains it.

I think we can ignore `set` library too.
