### ISSUE TITLE
Unable to run `rbs validate` with RBS 3.0.0, and RBS as a required dependency

### ISSUE THREAD

**Issue by hjwylde** [ruby/rbs#1258]
I'm getting this error when trying to run `rbs validate` about a duplicate method signature. From looking into it, it does seem there is now a duplicate of `parse_file` in `core/ruby_vm.rbs` and `sig/shims/_abstract_syntax_tree.rbs`. Let me know though if I have something set up incorrectly.

```
bundler: failed to load command: rbs (/Users/hjwylde/.rbenv/versions/3.2.1/bin/rbs)
/Users/hjwylde/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/rbs-3.0.1/lib/rbs/definition_builder/method_builder.rb:38:in `block in validate!': /Users/hjwylde/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/rbs-3.0.1/core/ruby_vm.rbs:111:2...111:110: ::RubyVM::AbstractSyntaxTree.parse has duplicated definitions in /Users/hjwylde/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/rbs-3.0.1/sig/shims/_abstract_syntax_tree.rbs:3:4...3:40 (RBS::DuplicatedMethodDefinitionError)
	from /Users/hjwylde/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/rbs-3.0.1/lib/rbs/definition_builder/method_builder.rb:36:in `each_value'
	from /Users/hjwylde/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/rbs-3.0.1/lib/rbs/definition_builder/method_builder.rb:36:in `validate!'
	from /Users/hjwylde/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/rbs-3.0.1/lib/rbs/definition_builder/method_builder.rb:170:in `build_singleton'
	from /Users/hjwylde/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/rbs-3.0.1/lib/rbs/definition_builder.rb:237:in `block (2 levels) in build_singleton0'
	from <internal:kernel>:90:in `tap'
	from /Users/hjwylde/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/rbs-3.0.1/lib/rbs/definition_builder.rb:220:in `block in build_singleton0'
	from /Users/hjwylde/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/rbs-3.0.1/lib/rbs/definition_builder.rb:740:in `try_cache'
	from /Users/hjwylde/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/rbs-3.0.1/lib/rbs/definition_builder.rb:213:in `build_singleton0'
	from /Users/hjwylde/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/rbs-3.0.1/lib/rbs/definition_builder.rb:291:in `block (2 levels) in build_singleton'
	from <internal:kernel>:90:in `tap'
	from /Users/hjwylde/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/rbs-3.0.1/lib/rbs/definition_builder.rb:290:in `block in build_singleton'
	from /Users/hjwylde/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/rbs-3.0.1/lib/rbs/definition_builder.rb:740:in `try_cache'
	from /Users/hjwylde/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/rbs-3.0.1/lib/rbs/definition_builder.rb:283:in `build_singleton'
	from /Users/hjwylde/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/rbs-3.0.1/lib/rbs/cli.rb:453:in `block in run_validate'
	from /Users/hjwylde/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/rbs-3.0.1/lib/rbs/cli.rb:448:in `each'
	from /Users/hjwylde/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/rbs-3.0.1/lib/rbs/cli.rb:448:in `run_validate'
	from /Users/hjwylde/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/rbs-3.0.1/lib/rbs/cli.rb:135:in `run'
	from /Users/hjwylde/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/rbs-3.0.1/exe/rbs:7:in `<top (required)>'
	from /Users/hjwylde/.rbenv/versions/3.2.1/bin/rbs:25:in `load'
	from /Users/hjwylde/.rbenv/versions/3.2.1/bin/rbs:25:in `<top (required)>'
	from /Users/hjwylde/.rbenv/versions/3.2.1/lib/ruby/3.2.0/bundler/cli/exec.rb:58:in `load'
	from /Users/hjwylde/.rbenv/versions/3.2.1/lib/ruby/3.2.0/bundler/cli/exec.rb:58:in `kernel_load'
	from /Users/hjwylde/.rbenv/versions/3.2.1/lib/ruby/3.2.0/bundler/cli/exec.rb:23:in `run'
	from /Users/hjwylde/.rbenv/versions/3.2.1/lib/ruby/3.2.0/bundler/cli.rb:491:in `exec'
	from /Users/hjwylde/.rbenv/versions/3.2.1/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/hjwylde/.rbenv/versions/3.2.1/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/hjwylde/.rbenv/versions/3.2.1/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Users/hjwylde/.rbenv/versions/3.2.1/lib/ruby/3.2.0/bundler/cli.rb:34:in `dispatch'
	from /Users/hjwylde/.rbenv/versions/3.2.1/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Users/hjwylde/.rbenv/versions/3.2.1/lib/ruby/3.2.0/bundler/cli.rb:28:in `start'
	from /Users/hjwylde/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/bundler-2.4.6/libexec/bundle:45:in `block in <top (required)>'
	from /Users/hjwylde/.rbenv/versions/3.2.1/lib/ruby/3.2.0/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /Users/hjwylde/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/bundler-2.4.6/libexec/bundle:33:in `<top (required)>'
	from /Users/hjwylde/.rbenv/versions/3.2.1/bin/bundle:25:in `load'
	from /Users/hjwylde/.rbenv/versions/3.2.1/bin/bundle:25:in `<main>'

Process finished with exit code 1.
```

**Comment by soutaro** [comment]
Thank you for reporting the problem. `$ rbs -r rbs validate` reproduced the issue.

Because we no longer need `sig/shims/_abstract_syntax_tree.rbs`, we should clean up the stubs.
