### ISSUE TITLE
collection install fails if it cannot find dependency

### ISSUE THREAD

**Issue by DalenW** [ruby/rbs#1260]
At least that's the best guess I have, not entirely sure what is causing this.

Error:
```
/Users/dalenw/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rbs-3.0.2/lib/rbs/collection/config/lockfile_generator.rb:135:in `block in assign_gem': undefined method `version' for nil:NilClass (NoMethodError)

            assign_gem(name: dep.name, version: spec.version, src_data: nil, ignored_gems: ignored_gems)
                                                    ^^^^^^^^
	from /Users/dalenw/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rbs-3.0.2/lib/rbs/collection/config/lockfile_generator.rb:133:in `each'
	from /Users/dalenw/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rbs-3.0.2/lib/rbs/collection/config/lockfile_generator.rb:133:in `assign_gem'
	from /Users/dalenw/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rbs-3.0.2/lib/rbs/collection/config/lockfile_generator.rb:79:in `block in generate'
	from /Users/dalenw/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rbs-3.0.2/lib/rbs/collection/config/lockfile_generator.rb:73:in `each'
	from /Users/dalenw/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rbs-3.0.2/lib/rbs/collection/config/lockfile_generator.rb:73:in `generate'
	from /Users/dalenw/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rbs-3.0.2/lib/rbs/collection/config/lockfile_generator.rb:27:in `generate'
	from /Users/dalenw/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rbs-3.0.2/lib/rbs/collection/config.rb:36:in `generate_lockfile'
	from /Users/dalenw/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rbs-3.0.2/lib/rbs/cli.rb:1068:in `run_collection'
	from /Users/dalenw/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rbs-3.0.2/lib/rbs/cli.rb:135:in `run'
	from /Users/dalenw/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rbs-3.0.2/exe/rbs:7:in `<top (required)>'
	from /Users/dalenw/.rbenv/versions/3.2.0/bin/rbs:25:in `load'
	from /Users/dalenw/.rbenv/versions/3.2.0/bin/rbs:25:in `<main
```

Gemfile (nothing exiting):
```ruby
# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.2.0"
gem "rbs_rails", require: false

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails', branch: 'main'
gem "rails", "~> 7.0.4"
# Use sqlite3 as the database for Active Record
gem "pg", "~> 1.4"
gem "mysql2"
# Use Puma as the app server
gem "puma", "~> 6.1"
# Use SCSS for stylesheets
gem "sass-rails", ">= 6"
# Sentry time! for error logging
gem "sentry-rails"
gem "sentry-ruby"
gem "sentry-sidekiq"
# Transpile app-like JavaScript. Read more: https://github.com/rails/webpacker
# gem "webpacker", "~> 5.0"
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem "jbuilder", "~> 2.7"

# Use Active Model has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Active Storage variant
# gem 'image_processing', '~> 1.2'

gem "doorkeeper", "~> 5.6.4"
# OmniAuth OAuth2
gem "omniauth-oauth2"
gem "omniauth-rails_csrf_protection"

# For name checking
gem "levenshtein"

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", ">= 1.4.4", require: false

# Money money money, its kinda funny, in a rich man's world
gem "money-rails", "~> 1.12"

group :development, :test do
  gem "figaro"
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem "byebug", platforms: %i[mri mingw x64_mingw]
  gem "rubocop"
  gem "rubocop-performance"
  gem "rubocop-rails_config"
end

group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem "web-console", ">= 4.1.0"
  # Display performance information such as SQL time and flame graphs for each request in your browser.
  # Can be configured to work on production as well see: https://github.com/MiniProfiler/rack-mini-profiler/blob/master/README.md
  gem "listen", "~> 3.8"
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem "spring"

  gem "rails-erd"
end

group :test do
  # Adds support for Capybara system testing and selenium driver
  gem "capybara", ">= 3.26"
  gem "selenium-webdriver"
  # Easy installation and use of web drivers to run system tests with browsers
  gem "webdrivers"
end

gem "actionpack-cloudflare"

gem "chronic_duration"
# gem "falcon"
gem "gaffe"
# Simple Encryption time
gem "lockbox"
gem "rest-client"
gem "stripe"

# Emails
gem "postmark-rails"

# Active links!
gem "active_link_to"

# front end
gem "sprockets-rails", require: "sprockets/railtie"
gem "importmap-rails"
gem "turbo-rails", "~> 1.3.3"
gem "stimulus-rails"

# UI
gem "view_component"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]
gem "wdm", ">= 0.1.0", platforms: %i[mingw mswin x64_mingw jruby]

# redis
gem "hiredis"
gem "redis"
gem "redis-namespace"
gem "redis-rack-cache"

# stay on version 6
gem "sidekiq", "~> 6.5.8"
gem "sidekiq-unique-jobs", "~> 7.1.0"

# searching
gem "typesense"

gem "data_migrate"

# message streaming
gem "bunny"

# notifications
gem "noticed"

# feature flags
gem "flipper"
gem "flipper-active_record"
gem "flipper-ui"
gem "flipper-api"

# profiling
gem "rails_mini_profiler"
gem "stackprof"

# country select
gem "country_select"
```

**Comment by soutaro** [comment]
Hi @DalenW,

Thank you for reporting the problem. I found there are several cases that `Gemfile.lock` doesn't have an entry for a gem.

1. `bundler` itself ([Rails still has Bundler as a dependency](https://github.com/rails/rails/blob/main/rails.gemspec#L45))
2. Gems that is not installed because of given `platforms:`

So, we will fix the problems and then release another version soon. Your `Gemfile` really helped! Thank you so much!

**Comment by DalenW** [comment]
You're welcome! I'm on arm (macos) so the platform thing can be a real issue. If you need my lockfile let me know.
