### ISSUE TITLE
RBS test in Ruby snapshot-master raises `ArgumentError`

### ISSUE THREAD

**Issue by nobu** [ruby/rbs#1315]
https://github.com/ruby/actions/actions/runs/4774175031/jobs/8487729344#step:18:322 and so on.
```
Error: test_instance_ancestors(RBS::AncestorBuilderTest): ArgumentError: wrong number of arguments (given 5, expected 4)
  /home/runner/work/actions/actions/snapshot-master/gems/src/rbs/lib/rbs/parser_aux.rb:7:in `_parse_type'
  /home/runner/work/actions/actions/snapshot-master/gems/src/rbs/lib/rbs/parser_aux.rb:7:in `parse_type'
  /home/runner/work/actions/actions/snapshot-master/gems/src/rbs/test/test_helper.rb:46:in `parse_type'
  /home/runner/work/actions/actions/snapshot-master/gems/src/rbs/test/rbs/ancestor_builder_test.rb:350:in `block (4 levels) in test_instance_ancestors'
       347:           a.ancestors[1].tap do |ancestor|
       348:             assert_instance_of Ancestor::Instance, ancestor
       349:             assert_equal TypeName("::Bar"), ancestor.name
    => 350:             assert_equal [Types::Variable.build(:X), parse_type("::String")], ancestor.args
       351:             assert_instance_of AST::Members::Include, ancestor.source
       352:           end
       353:           a.ancestors[2].tap do |ancestor|
  <internal:kernel>:90:in `tap'
  /home/runner/work/actions/actions/snapshot-master/gems/src/rbs/test/rbs/ancestor_builder_test.rb:347:in `block (3 levels) in test_instance_ancestors'
  <internal:kernel>:90:in `tap'
  /home/runner/work/actions/actions/snapshot-master/gems/src/rbs/test/rbs/ancestor_builder_test.rb:336:in `block (2 levels) in test_instance_ancestors'
  /home/runner/work/actions/actions/snapshot-master/gems/src/rbs/test/test_helper.rb:175:in `block in build'
  /home/runner/work/actions/actions/snapshot-master/lib/tmpdir.rb:94:in `mktmpdir'
  /home/runner/work/actions/actions/snapshot-master/gems/src/rbs/test/test_helper.rb:156:in `build'
  /home/runner/work/actions/actions/snapshot-master/gems/src/rbs/test/rbs/ancestor_builder_test.rb:246:in `block in test_instance_ancestors'
  /home/runner/work/actions/actions/snapshot-master/gems/src/rbs/test/test_helper.rb:90:in `new'
  /home/runner/work/actions/actions/snapshot-master/gems/src/rbs/test/rbs/ancestor_builder_test.rb:234:in `test_instance_ancestors'
```

**Comment by soutaro** [comment]
I think that was fixed.
