### ISSUE TITLE
`RBS::DuplicatedMethodDefinitionError` for conflicting rbs in `meta-tags` and `activesupport`

### ISSUE THREAD

**Issue by tanmoysrt** [ruby/rbs#1359]
`meta-tags` has some rbs for `Object` and `Hash` class. [Check here](https://github.com/kpumuk/meta-tags/blob/main/sig/lib/_internal/rails.rbs). It's conflicting with many rbs of [ `gem_rbs_collection`](https://github.com/ruby/gem_rbs_collection) while running `rbs validate`

```
Validating class/module definition: `::Array`...
/usr/share/rvm/gems/ruby-3.2.0/gems/rbs-3.1.0/lib/rbs/definition_builder/method_builder.rb:38:in `block in validate!': /home/tanmoy/Desktop/oss/CircuitVerse/.gem_rbs_collection/activesupport/7.0/activesupport-generated.rbs:4510:2...4510:27: ::Object#blank? has duplicated definitions in /usr/share/rvm/gems/ruby-3.2.0/gems/meta-tags-2.16.0/sig/lib/_rails.rbs:8:2...8:24 (RBS::DuplicatedMethodDefinitionError)

    def blank?: () -> untyped
    ^^^^^^^^^^^^^^^^^^^^^^^^^

        from /usr/share/rvm/gems/ruby-3.2.0/gems/rbs-3.1.0/lib/rbs/definition_builder/method_builder.rb:36:in `each_value'
        from /usr/share/rvm/gems/ruby-3.2.0/gems/rbs-3.1.0/lib/rbs/definition_builder/method_builder.rb:36:in `validate!'
        from /usr/share/rvm/gems/ruby-3.2.0/gems/rbs-3.1.0/lib/rbs/definition_builder/method_builder.rb:141:in `build_instance'
        from /usr/share/rvm/gems/ruby-3.2.0/gems/rbs-3.1.0/lib/rbs/definition_builder.rb:168:in `block (2 levels) in build_instance'
        from <internal:kernel>:90:in `tap'
        from /usr/share/rvm/gems/ruby-3.2.0/gems/rbs-3.1.0/lib/rbs/definition_builder.rb:166:in `block in build_instance'
        from /usr/share/rvm/gems/ruby-3.2.0/gems/rbs-3.1.0/lib/rbs/definition_builder.rb:748:in `try_cache'
        from /usr/share/rvm/gems/ruby-3.2.0/gems/rbs-3.1.0/lib/rbs/definition_builder.rb:158:in `build_instance'
        from /usr/share/rvm/gems/ruby-3.2.0/gems/rbs-3.1.0/lib/rbs/definition_builder.rb:176:in `block (2 levels) in build_instance'
        from <internal:kernel>:90:in `tap'
        from /usr/share/rvm/gems/ruby-3.2.0/gems/rbs-3.1.0/lib/rbs/definition_builder.rb:166:in `block in build_instance'
        from /usr/share/rvm/gems/ruby-3.2.0/gems/rbs-3.1.0/lib/rbs/definition_builder.rb:748:in `try_cache'
        from /usr/share/rvm/gems/ruby-3.2.0/gems/rbs-3.1.0/lib/rbs/definition_builder.rb:158:in `build_instance'
        from /usr/share/rvm/gems/ruby-3.2.0/gems/rbs-3.1.0/lib/rbs/cli.rb:467:in `block in run_validate'
        from /usr/share/rvm/gems/ruby-3.2.0/gems/rbs-3.1.0/lib/rbs/cli.rb:465:in `each'
        from /usr/share/rvm/gems/ruby-3.2.0/gems/rbs-3.1.0/lib/rbs/cli.rb:465:in `run_validate'
        from /usr/share/rvm/gems/ruby-3.2.0/gems/rbs-3.1.0/lib/rbs/cli.rb:137:in `run'
        from /usr/share/rvm/gems/ruby-3.2.0/gems/rbs-3.1.0/exe/rbs:7:in `<top (required)>'
        from /usr/share/rvm/gems/ruby-3.2.0/bin/rbs:25:in `load'
        from /usr/share/rvm/gems/ruby-3.2.0/bin/rbs:25:in `<main>'
        from /usr/share/rvm/gems/ruby-3.2.0/bin/ruby_executable_hooks:22:in `eval'
        from /usr/share/rvm/gems/ruby-3.2.0/bin/ruby_executable_hooks:22:in `<main>'
```

I am searching to exclude specific rbs definition of any gem via some configuration via `steepfile` or `rbs_collection.yaml` but haven't find any solution

**Comment by tanmoysrt** [comment]
@pocke can you help to resolve this issue ?

**Comment by soutaro** [comment]
It looks like the canonical way is to upgrade meta-tags, the latest version is 2.18.0 and it doesn't have the `_rails.rbs` file.

If you really need another workaround, you can tell `rbs collection` to skip loading `meta-tags` automatically, and set up loading type definitions yourself.

```yaml
# rbs_collection.yml
gems:
  - name: meta-tags    # Skip loading meta-tags library automatically
    ignore: true
```

```ruby
# Steepfile

target ... do
  # Manually load the bundled RBS files, but ignore the `_rails.rbs`
  meta_tags_path = Gem::Specification.find_by_name("meta_tags").gem_dir
  rbs_files = Pathname.glob(File.join(meta_tags_path, "sig/**/*.rbs")).reject {|path| path.basename.to_s == "_rails.rbs" }
  signature *rbs_files
end
```

**Comment by tanmoysrt** [comment]
> 

Thanks for your reply.
I was trying out the second solution.
While executing `signature *rbs_files` line, it;s throwing undefined method `delete_prefix`
Stacktrace -
```
#<NoMethodError: undefined method `delete_prefix' for #<Pathname:/usr/share/rvm/gems/ruby-3.2.0/gems/meta-tags-2.16.0/sig/lib/meta_tags/configuration.rbs>>
  /usr/share/rvm/gems/ruby-3.2.0/gems/steep-1.4.0/lib/steep/project/pattern.rb:19:in `block in initialize'
  /usr/share/rvm/gems/ruby-3.2.0/gems/steep-1.4.0/lib/steep/project/pattern.rb:15:in `map'
  /usr/share/rvm/gems/ruby-3.2.0/gems/steep-1.4.0/lib/steep/project/pattern.rb:15:in `initialize'
  /usr/share/rvm/gems/ruby-3.2.0/gems/steep-1.4.0/lib/steep/project/dsl.rb:228:in `new'
  /usr/share/rvm/gems/ruby-3.2.0/gems/steep-1.4.0/lib/steep/project/dsl.rb:228:in `target'
  Steepfile:3:in `block in parse'
  /usr/share/rvm/gems/ruby-3.2.0/gems/steep-1.4.0/lib/steep/project/dsl.rb:211:in `instance_eval'
  /usr/share/rvm/gems/ruby-3.2.0/gems/steep-1.4.0/lib/steep/project/dsl.rb:211:in `block in parse'
  /usr/share/rvm/gems/ruby-3.2.0/gems/activesupport-7.0.5/lib/active_support/tagged_logging.rb:99:in `block in tagged'
  /usr/share/rvm/gems/ruby-3.2.0/gems/activesupport-7.0.5/lib/active_support/tagged_logging.rb:37:in `tagged'
  /usr/share/rvm/gems/ruby-3.2.0/gems/activesupport-7.0.5/lib/active_support/tagged_logging.rb:99:in `tagged'
  /usr/share/rvm/gems/ruby-3.2.0/gems/steep-1.4.0/lib/steep/project/dsl.rb:210:in `parse'
  /usr/share/rvm/gems/ruby-3.2.0/gems/steep-1.4.0/lib/steep/drivers/utils/driver_helper.rb:12:in `block in load_config'
  <internal:kernel>:90:in `tap'
  /usr/share/rvm/gems/ruby-3.2.0/gems/steep-1.4.0/lib/steep/drivers/utils/driver_helper.rb:11:in `load_config'
  /usr/share/rvm/gems/ruby-3.2.0/gems/steep-1.4.0/lib/steep/drivers/check.rb:25:in `run'
  /usr/share/rvm/gems/ruby-3.2.0/gems/steep-1.4.0/lib/steep/cli.rb:120:in `process_check'
  /usr/share/rvm/gems/ruby-3.2.0/gems/steep-1.4.0/lib/steep/cli.rb:60:in `run'
  /usr/share/rvm/gems/ruby-3.2.0/gems/steep-1.4.0/exe/steep:11:in `<top (required)>'
  /usr/share/rvm/gems/ruby-3.2.0/bin/steep:25:in `load'
  /usr/share/rvm/gems/ruby-3.2.0/bin/steep:25:in `<main>'
  /usr/share/rvm/gems/ruby-3.2.0/bin/ruby_executable_hooks:22:in `eval'
  /usr/share/rvm/gems/ruby-3.2.0/bin/ruby_executable_hooks:22:in `<main>'
```

I am using Ruby 3.2.0 & meta-tags 2.16.0

**Comment by soutaro** [comment]
Ah, you need to convert `Pathname` to `String`...

However, I found directly adding the files with `signature` may not work. So, my updated workaround suggestion is copy the RBS files from the meta-tags repository to your repository, as something like `sig/vendor/meta-tags`.

**Comment by tanmoysrt** [comment]
> Ah, you need to convert `Pathname` to `String`...
> 
> However, I found directly adding the files with `signature` may not work. So, my updated workaround suggestion is copy the RBS files from the meta-tags repository to your repository, as something like `sig/vendor/_meta-tags/`.

Ok got it. 
Thank you
