### ISSUE TITLE
Can't make extension for Enumerable

### ISSUE THREAD

**Issue by pocke** [ruby/rbs#305]
An error occurred when I tried to make an extension for Enumerable.

```ruby
# rbs

extension Enumerable[Elem, Return] (test)
end
```

```bash
$ rbs -I . validate
(snip)
/path/rbs-0.3.1/stdlib/builtin/hash.rbs:108:0...1029:3:    Validating class/module definition: `::Hash`...
/path/rbs-0.3.1/lib/rbs/definition_builder.rb:70:in `map': undefined method `name' for #<RBS::Types::Tuple:0x000055d61d606780 @types=[#<RBS::Types::Variable:0x000055d61d613ae8 @name=:K, @location=nil>, #<RBS::Types::Variable:0x000055d
61d613980 @name=:V, @location=nil>], @location=#<RBS::Location:380 @buffer=/path/rbs-0.3.1/stdlib/builtin/hash.rbs, @pos=3152...3158, source='[K, V]', start_line=109, start_column=21>> (NoMethodError)
        from /path/rbs-0.3.1/lib/rbs/definition_builder.rb:70:in `block in build_ancestors'
        from /path/rbs-0.3.1/lib/rbs/definition_builder.rb:65:in `each'
        from /path/rbs-0.3.1/lib/rbs/definition_builder.rb:65:in `build_ancestors'
        from /path/rbs-0.3.1/lib/rbs/definition_builder.rb:58:in `block in build_ancestors'
        from /path/rbs-0.3.1/lib/rbs/definition_builder.rb:50:in `each'
        from /path/rbs-0.3.1/lib/rbs/definition_builder.rb:50:in `build_ancestors'
        from /path/rbs-0.3.1/lib/rbs/definition_builder.rb:210:in `block in build_instance'
        from /path/rbs-0.3.1/lib/rbs/definition_builder.rb:811:in `try_cache'
        from /path/rbs-0.3.1/lib/rbs/definition_builder.rb:202:in `build_instance'
        from /path/rbs-0.3.1/lib/rbs/cli.rb:308:in `block in run_validate'
        from /path/rbs-0.3.1/lib/rbs/environment.rb:70:in `block in each_decl'
        from /path/rbs-0.3.1/lib/rbs/environment.rb:69:in `each'
        from /path/rbs-0.3.1/lib/rbs/environment.rb:69:in `each_decl'
        from /path/rbs-0.3.1/lib/rbs/cli.rb:304:in `run_validate'
        from /path/rbs-0.3.1/lib/rbs/cli.rb:85:in `run'
        from /path/rbs-0.3.1/exe/rbs:7:in `<top (required)>'
        from /path2/bin/rbs:23:in `load'
        from /path2/bin/rbs:23:in `<main>'
```

The error message points Hash.rbs.
https://github.com/ruby/rbs/blob/0c9e64e78f3d3a9fa06a1dfec8b8896cf1f5198d/stdlib/builtin/hash.rbs#L109

It looks `[K, V]` is the cause.

**Comment by pocke** [comment]
`extension` syntax has been removed, and the following RBS is valid.

```rbs
module Enumerable[unchecked out Elem]
end
```

So I'll close this issue.
