### ISSUE TITLE
NoMethodError via `rbs prototype runtime -r rexml/document REXML`

### ISSUE THREAD

**Issue by ybiquitous** [ruby/rbs#446]
When I try getting prototype of the `REXML` type via `rbs prototype`, I find that the following `NoMethodError` occurs:

```
/usr/local/lib/ruby/gems/2.7.0/gems/rexml-3.2.4/lib/rexml/functions.rb:89:in `get_namespace': undefined method `[]' for nil:NilClass (NoMethodError)
```

The cause seems to me that `REXML::Functions.name` redefines [`Module.name`](https://ruby-doc.org/core-2.7.2/Module.html#name-method):

https://github.com/ruby/rexml/blob/v3.2.4/lib/rexml/functions.rb#L80

Is there a way to avoid this error?

## Reproduction

```console
$ docker run --rm -it rubylang/ruby:2.7.2-bionic bash
(...)

$ ruby -v
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]

$ gem install rexml rbs
(...)

$ ruby -r rexml/document -e 'puts REXML::VERSION'
3.2.4

$ rbs -v
rbs 0.14.0

$ rbs prototype runtime -r rexml/document REXML
Traceback (most recent call last):
	14: from /usr/local/bin/rbs:23:in `<main>'
	13: from /usr/local/bin/rbs:23:in `load'
	12: from /usr/local/lib/ruby/gems/2.7.0/gems/rbs-0.14.0/exe/rbs:7:in `<top (required)>'
	11: from /usr/local/lib/ruby/gems/2.7.0/gems/rbs-0.14.0/lib/rbs/cli.rb:98:in `run'
	10: from /usr/local/lib/ruby/gems/2.7.0/gems/rbs-0.14.0/lib/rbs/cli.rb:590:in `run_prototype'
	 9: from /usr/local/lib/ruby/gems/2.7.0/gems/rbs-0.14.0/lib/rbs/prototype/runtime.rb:40:in `decls'
	 8: from /usr/local/lib/ruby/gems/2.7.0/gems/rbs-0.14.0/lib/rbs/prototype/runtime.rb:40:in `select'
	 7: from /usr/local/lib/ruby/gems/2.7.0/gems/rbs-0.14.0/lib/rbs/prototype/runtime.rb:40:in `each'
	 6: from /usr/local/lib/ruby/gems/2.7.0/gems/rbs-0.14.0/lib/rbs/prototype/runtime.rb:40:in `each_object'
	 5: from /usr/local/lib/ruby/gems/2.7.0/gems/rbs-0.14.0/lib/rbs/prototype/runtime.rb:40:in `block in decls'
	 4: from /usr/local/lib/ruby/gems/2.7.0/gems/rbs-0.14.0/lib/rbs/prototype/runtime.rb:20:in `target?'
	 3: from /usr/local/lib/ruby/gems/2.7.0/gems/rbs-0.14.0/lib/rbs/prototype/runtime.rb:20:in `any?'
	 2: from /usr/local/lib/ruby/gems/2.7.0/gems/rbs-0.14.0/lib/rbs/prototype/runtime.rb:24:in `block in target?'
	 1: from /usr/local/lib/ruby/gems/2.7.0/gems/rexml-3.2.4/lib/rexml/functions.rb:81:in `name'
/usr/local/lib/ruby/gems/2.7.0/gems/rexml-3.2.4/lib/rexml/functions.rb:89:in `get_namespace': undefined method `[]' for nil:NilClass (NoMethodError)
```

## Environment

- Ruby 2.7.2
- RBS 0.14.0
- REXML 3.2.4

**Comment by ybiquitous** [comment]
I found a way to avoid the error (but I'm not confident...), so I've opened PR #447.
