### ISSUE TITLE
rbs/test: stack level too deep when having super call

### ISSUE THREAD

**Issue by palkan** [ruby/rbs#478]
Due to the usage of the alias method chain approach (https://github.com/ruby/rbs/blob/7914225ae9d75367449a15fa46db91f5b3c4fbe7/lib/rbs/test/hook.rb#L48), invoking `super` from a method causes `stack level too deep` in case both parent and child classes have signatures defined for the method.

Example:

```ruby
# a.rb
class A
  def foo
    "bar"
  end
end

class B < A
  def foo
    super.size
  end
end

p B.new.foo

# sig/a.rbs
class A
  def foo: () -> String
end

class B < A
  def foo: () -> Integer
end
```

Run:

```sh
$ RBS_TEST_TARGET='A,B' ruby -r rbs/test/setup a.rb

I, [2020-11-19T09:41:59.154893 #177]  INFO -- : Setting up hooks for ::A
I, [2020-11-19T09:41:59.155009 #177]  INFO -- rbs: Installing runtime type checker in A...
I, [2020-11-19T09:41:59.162527 #177]  INFO -- rbs: Setting up method hook in #foo...
I, [2020-11-19T09:41:59.166309 #177]  INFO -- : Setting up hooks for ::B
I, [2020-11-19T09:41:59.166368 #177]  INFO -- rbs: Installing runtime type checker in B...
I, [2020-11-19T09:41:59.167210 #177]  INFO -- rbs: Setting up method hook in #foo...
/usr/local/lib/ruby/gems/3.0.0/gems/rbs-0.17.0/lib/rbs/test/type_check.rb:74:in `args': stack level too deep (SystemStackError)
        from /usr/local/lib/ruby/gems/3.0.0/gems/rbs-0.17.0/lib/rbs/test/type_check.rb:46:in `method_call'
        from /usr/local/lib/ruby/gems/3.0.0/gems/rbs-0.17.0/lib/rbs/test/type_check.rb:23:in `block in overloaded_call'
        from /usr/local/lib/ruby/gems/3.0.0/gems/rbs-0.17.0/lib/rbs/test/type_check.rb:22:in `map'
        from /usr/local/lib/ruby/gems/3.0.0/gems/rbs-0.17.0/lib/rbs/test/type_check.rb:22:in `overloaded_call'
```

**Comment by soutaro** [comment]
I believe this is fixed in #489.
