### ISSUE TITLE
Cant use "type:" in record declaratio

### ISSUE THREAD

**Issue by HoneyryderChuck** [ruby/rbs#512]
Using `type:` in record declaration isn't recognized by the parser.

```ruby
# this parses
type bla = { bla: 1 }
# this doesn't
type bla = { type: 1 }
```

```
# backtrace
from (eval):3:in `_racc_do_parse_c'
        from (eval):3:in `do_parse'
        from parser.y:1132:in `parse_signature'
        from /usr/local/bundle/bundler/gems/rbs-71b8e534e0ad/lib/rbs/environment_loader.rb:123:in `block (2 levels) in each_decl'
        from /usr/local/bundle/bundler/gems/rbs-71b8e534e0ad/lib/rbs/environment_loader.rb:93:in `each_file'
        from /usr/local/bundle/bundler/gems/rbs-71b8e534e0ad/lib/rbs/environment_loader.rb:106:in `block in each_file'
        from /usr/local/bundle/bundler/gems/rbs-71b8e534e0ad/lib/rbs/environment_loader.rb:105:in `each'
        from /usr/local/bundle/bundler/gems/rbs-71b8e534e0ad/lib/rbs/environment_loader.rb:105:in `each_file'
        from /usr/local/bundle/bundler/gems/rbs-71b8e534e0ad/lib/rbs/environment_loader.rb:117:in `block in each_decl'
        from /usr/local/bundle/bundler/gems/rbs-71b8e534e0ad/lib/rbs/environment_loader.rb:85:in `block in each_dir'
        from /usr/local/bundle/bundler/gems/rbs-71b8e534e0ad/lib/rbs/environment_loader.rb:84:in `each'
        from /usr/local/bundle/bundler/gems/rbs-71b8e534e0ad/lib/rbs/environment_loader.rb:84:in `each_dir'
        from /usr/local/bundle/bundler/gems/rbs-71b8e534e0ad/lib/rbs/environment_loader.rb:114:in `each_decl'

**Comment by soutaro** [comment]
🙇‍♂️
