### ISSUE TITLE
[bug] "rbs prototype rb" fails on endless method definitions 

### ISSUE THREAD

**Issue by 0exp** [ruby/rbs#551]
Hello, Ruby Core Team! Thank you for your great work! :)

---

I found an issue with a `rbs prototype rb` command that fails on endless method definitions.

Imagine we have a simple code (`lib/encodable.rb`):

```ruby
# frozen_string_literal: true

require 'base64'

module Encodable
  def encode
    Base64.encode64(self.to_s)
  end
end
```

With `rbs prototye rb lib/encodable.rb` rbs works great:

```shell
➜ rbs prototype rb lib/encodable.rb

module Encodable
  def encode: () -> untyped
end
```

When i rewrote this code with an endless method definition style:

```ruby
# frozen_string_literal: true

require 'base64'

module Encodable
  def encode = Base64.encode64(self.to_s)
end
```

`rbs prototye rb lib/encodable.rb` fails with an errror:

```shell
➜ rbs prototype rb lib/encodable.rb
/Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rbs-1.0.0/lib/rbs/prototype/rb.rb:383:in `function_type_from_body': undefined method `children' for nil:NilClass (NoMethodError)
	from /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rbs-1.0.0/lib/rbs/prototype/rb.rb:151:in `process'
	from /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rbs-1.0.0/lib/rbs/prototype/rb.rb:336:in `block in process_children'
	from /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rbs-1.0.0/lib/rbs/prototype/rb.rb:371:in `block in each_node'
	from /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rbs-1.0.0/lib/rbs/prototype/rb.rb:369:in `each'
	from /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rbs-1.0.0/lib/rbs/prototype/rb.rb:369:in `each_node'
	from /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rbs-1.0.0/lib/rbs/prototype/rb.rb:377:in `each_child'
	from /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rbs-1.0.0/lib/rbs/prototype/rb.rb:335:in `process_children'
	from /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rbs-1.0.0/lib/rbs/prototype/rb.rb:330:in `process'
	from /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rbs-1.0.0/lib/rbs/prototype/rb.rb:336:in `block in process_children'
	from /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rbs-1.0.0/lib/rbs/prototype/rb.rb:371:in `block in each_node'
	from /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rbs-1.0.0/lib/rbs/prototype/rb.rb:369:in `each'
	from /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rbs-1.0.0/lib/rbs/prototype/rb.rb:369:in `each_node'
	from /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rbs-1.0.0/lib/rbs/prototype/rb.rb:377:in `each_child'
	from /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rbs-1.0.0/lib/rbs/prototype/rb.rb:335:in `process_children'
	from /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rbs-1.0.0/lib/rbs/prototype/rb.rb:330:in `process'
	from /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rbs-1.0.0/lib/rbs/prototype/rb.rb:121:in `block in process'
	from /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rbs-1.0.0/lib/rbs/prototype/rb.rb:371:in `block in each_node'
	from /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rbs-1.0.0/lib/rbs/prototype/rb.rb:369:in `each'
	from /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rbs-1.0.0/lib/rbs/prototype/rb.rb:369:in `each_node'
	from /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rbs-1.0.0/lib/rbs/prototype/rb.rb:120:in `process'
	from /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rbs-1.0.0/lib/rbs/prototype/rb.rb:336:in `block in process_children'
	from /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rbs-1.0.0/lib/rbs/prototype/rb.rb:371:in `block in each_node'
	from /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rbs-1.0.0/lib/rbs/prototype/rb.rb:369:in `each'
	from /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rbs-1.0.0/lib/rbs/prototype/rb.rb:369:in `each_node'
	from /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rbs-1.0.0/lib/rbs/prototype/rb.rb:377:in `each_child'
	from /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rbs-1.0.0/lib/rbs/prototype/rb.rb:335:in `process_children'
	from /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rbs-1.0.0/lib/rbs/prototype/rb.rb:330:in `process'
	from /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rbs-1.0.0/lib/rbs/prototype/rb.rb:336:in `block in process_children'
	from /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rbs-1.0.0/lib/rbs/prototype/rb.rb:371:in `block in each_node'
	from /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rbs-1.0.0/lib/rbs/prototype/rb.rb:369:in `each'
	from /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rbs-1.0.0/lib/rbs/prototype/rb.rb:369:in `each_node'
	from /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rbs-1.0.0/lib/rbs/prototype/rb.rb:377:in `each_child'
	from /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rbs-1.0.0/lib/rbs/prototype/rb.rb:335:in `process_children'
	from /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rbs-1.0.0/lib/rbs/prototype/rb.rb:330:in `process'
	from /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rbs-1.0.0/lib/rbs/prototype/rb.rb:79:in `parse'
	from /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rbs-1.0.0/lib/rbs/cli.rb:661:in `block in run_prototype_file'
	from /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rbs-1.0.0/lib/rbs/cli.rb:660:in `each'
	from /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rbs-1.0.0/lib/rbs/cli.rb:660:in `run_prototype_file'
	from /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rbs-1.0.0/lib/rbs/cli.rb:550:in `run_prototype'
	from /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rbs-1.0.0/lib/rbs/cli.rb:113:in `run'
	from /Users/exclusive/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rbs-1.0.0/exe/rbs:7:in `<top (required)>'
	from /Users/exclusive/.rbenv/versions/3.0.0/bin/rbs:23:in `load'
	from /Users/exclusive/.rbenv/versions/3.0.0/bin/rbs:23:in `<main>'
```

---

```
ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin20]
```

```
RUBY_VERSION: 3.0.0
RUBY_ENGINE_VERSION: 3.0.0
RUBY_PLATFORM: x86_64-darwin20
RUBY_REVISION: 95aff214687a5e12c3eb57d056665741e734c188
```

```
rbs version: 1.0.0
rbenv version: 1.1.2
```

---

In addition, typeprof works great:

```shell
➜ typeprof lib/encodable.rb
# Classes
module Encodable
  def encode: -> String
end
```

```
typeprof version: 0.11.0
```

---

Sorry, if this issue already in progress. If it is - please, close my issue :)

**Comment by pocke** [comment]
Thanks for the bug report! @0exp 

I guess it is a bug of Ruby, so I opened a pull request for this problem. https://github.com/ruby/ruby/pull/4016

But I guess we need a patch for this problem to `rbs prototype rb` also because it is still a problem until Ruby 3.0.1. So I'll work on it :muscle:
