### ISSUE TITLE
redefinition of #initialize in prepend module leads to stack level too deep

### ISSUE THREAD

**Issue by HoneyryderChuck** [ruby/rbs#607]
In an example similar to this, I have:

```ruby
class A
  prepend B

  def initialize(foo: )
    ...

  end
end

module B
   def initialize(bar: , **opts)
     super(**opts)
   end
end
```

when running with runtime type-checking, I get smth similar to this stack trace:

```
 # /usr/local/bundle/bundler/gems/rbs-d71e3415ef63/lib/rbs/test/hook.rb:138:in `initialize__with__RBS_TEST_1921f7_a6b20500'
     # ./lib/netsnmp/loggable.rb:9:in `initialize'
     # /usr/local/bundle/bundler/gems/rbs-d71e3415ef63/lib/rbs/test/hook.rb:138:in `initialize__with__RBS_TEST_1921f7_a6b20500'
     # ./lib/netsnmp/loggable.rb:9:in `initialize'
     # /usr/local/bundle/bundler/gems/rbs-d71e3415ef63/lib/rbs/test/hook.rb:138:in `initialize__with__RBS_TEST_1921f7_a6b20500'
     # ./lib/netsnmp/loggable.rb:9:in `initialize'
     # /usr/local/bundle/bundler/gems/rbs-d71e3415ef63/lib/rbs/test/hook.rb:138:in `initialize__with__RBS_TEST_1921f7_a6b20500'
     # ./lib/netsnmp/loggable.rb:9:in `initialize'
     # /usr/local/bundle/bundler/gems/rbs-d71e3415ef63/lib/rbs/test/hook.rb:138:in `initialize__with__RBS_TEST_1921f7_a6b20500'
     # ./lib/netsnmp/loggable.rb:9:in `initialize'
     # /usr/local/bundle/bundler/gems/rbs-d71e3415ef63/lib/rbs/test/hook.rb:138:in `initialize__with__RBS_TEST_1921f7_a6b20500'
     # ./lib/netsnmp/loggable.rb:9:in `initialize'
     # /usr/local/bundle/bundler/gems/rbs-d71e3415ef63/lib/rbs/test/hook.rb:138:in `initialize__with__RBS_TEST_1921f7_a6b20500'
     # ./lib/netsnmp/loggable.rb:9:in `initialize'
     # /usr/local/bundle/bundler/gems/rbs-d71e3415ef63/lib/rbs/test/hook.rb:138:in `initialize__with__RBS_TEST_1921f7_a6b20500'
     # ./lib/netsnmp/loggable.rb:9:in `initialize'
     # /usr/local/bundle/bundler/gems/rbs-d71e3415ef63/lib/rbs/test/hook.rb:138:in `initialize__with__RBS_TEST_1921f7_a6b20500'
     # ./lib/netsnmp/loggable.rb:9:in `initialize'
```

The call stack seems to be:

* `initialize` gets called, enters the prepended `initialize`;
*  prepended `initialize` calls `super`, goes to rbs alias hook;
* the `rbs` alias hook calls `super`, goes back to prepended `initialize`;

The original `initialize` never gets called.

**Comment by HoneyryderChuck** [comment]
ok, the issue is gone if I define a sig for the module and  `prepend` in the interface as well.

**Comment by soutaro** [comment]
@HoneyryderChuck I'm sorry that I couldn't reply... I know using both of the runtime type checking and mixin sometimes breaks the app. I don't think we can fix the issue completely for a while.
